name: run tests

on:
  push:
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run tests for Gradle plugin breitbandausbaumonitor-archiver
        run: ./gradlew test
        working-directory: archiver
