name: update frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.WORKFLOW_SSH_KEY }}

      - name: Set up Volta
        uses: volta-cli/action@v1

      - name: Build front end
        run: ./gradlew buildFrontend

      - uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.WORKFLOW_SSH_KEY }}

      - name: Set Git author information
        run: |
          git config --global user.name "chkpnt CI"
          git config --global user.email "chkpnt-ci@chkpnt.de"

      - name: Publish front end to GitHub Pages
        run: ./gradlew frontend:gitPublishPush
