name: update frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.WORKFLOW_SSH_KEY }}

      - name: Set up Volta
        uses: volta-cli/action@v1

      - name: Build front end
        run: ./gradlew buildFrontend
      
