name: auto-updating coverage

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  update-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.WORKFLOW_SSH_KEY }}
      - name: Set up Java environment
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Download current coverage overlay
        run: ./gradlew downloadCurrentCoverageOverlay

      - name: Set Git author information
        run: |
          git config --global user.name "chkpnt CI"
          git config --global user.email "chkpnt-ci@chkpnt.de"

      - uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: ${{ secrets.WORKFLOW_SSH_KEY }}
      - name: Push data, if there are any changes
        run: ./gradlew gitPublishPush --info
