name: update overlays

on:
  workflow_dispatch:
  repository_dispatch:
    types: [ update_overlays ]

jobs:
  update-coverage:
    runs-on: zimmermann
    steps:
      - uses: actions/checkout@v3
        with:
          ssh-key: ${{ secrets.WORKFLOW_SSH_KEY }}

      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.WORKFLOW_SSH_KEY }}

      - name: Update all coverage overlays in a locally cloned Breitbandausbaumonitor repository
        run: ./gradlew updateAllCoverageMaps

      - name: Set Git author information
        run: |
          git config --global user.name "chkpnt CI"
          git config --global user.email "chkpnt-ci@chkpnt.de"

      - name: Commit and push repository, if there are any changes
        run: ./gradlew repoCommit repoPush --info
